url: https://www.sophiamcclennen.com
sitename: 'Sophia A. McClennen'
title: 'Sophia A. McClennen'
description: 'Sophia A. McClennen works on the intersections between culture, politics, and society. Her books focus on cultural responses to complex social change, such as the connections between the satire of Stephen Colbert and post 9/11 politics or the exile writing of Ariel Dorfman and dictatorship in 1970s Latin America.'
author:
  twitter: mcclennen65
  picture: /assets/img/sophia-3.jpg

# do not include  https://github.com/...
encoding: utf-8
#Pages - store all pages in the _pages directory
include: ['_pages']

exclude: ['readme.md','license.md','Gemfile', 'Gemfile.lock','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'README.md', 'prose.yaml']
version: 3.2.1
# dev options (true/false)
# if site is in production, 'production: true'
production: true
bust_css_cache: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# options (data)
google_analytics_id: UA-21655936-27
disqus_id:
addthis_id: ra-5434c4d85c06c266

# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:
path_assets_images: /assets/img/

# options (social)
# facebook_id:
twitter_id: mcclennen65
permalink: /:categories/:title/
categories:
  - what-im-watching
  - news

category_names:
  - name: "What I'm Watching"
    slug:
  - name: "News"
    slug: "news"


sass:
  style: :compressed
  sass_dir: assets/css/_sass

collections:
  books:
    output: true
    permalink: /book/:path/
  reviews:
    output: false
  writing:
    output: false
defaults:
  -
    scope:
      path: ""
      type: 'pages'
    values:
      layout: 'page'
  -
    scope:
      path: "_books"
      type: 'books'
    values:
      layout: 'book'
      section: 'book'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

#configuration options for http://prose.io editor
prose:
  siteurl: 'http://www.sophiamcclennen.com/'
  media: 'assets/img'
  ignore:
    - .gitignore
    - .bowerrc
    - .editorconfig
    - bower.json
    - 404.html
    - CNAME
    - atom.xml
    - favicon.ico
    - license.md
    - readme.md
    - gemfile
    - Gemfile.lock
    - robots.txt
    - _config.yml
    - _prose.yml
    - /assets
    - /_layouts
    - /_includes
    - /_site
    - /_data
  metadata:
    _what-im-watching/_posts:
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
          placeholder: 'Title'
          value: ''
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: 'publication'
        field:
          element: 'text'
          label: "Publication"
          help: "Name of the source publication"
    _pages:
        - name: 'layout'
          field:
            element: 'hidden'
            value: 'page'
        - name: 'title'
          field:
            element: 'text'
            label: 'Title'
            placeholder: 'Title'
            value: 'Title'
        - name: 'permalink'
          field:
            element: 'text'
            label: 'Link'
            help: '/page-name/'
        - name: 'include'
          field:
            label: 'Include Snippet'
            element: 'text'
            help: 'for developer use only'            
        - name: 'sharing'
          field:
            element: 'checkbox'
            label: 'Add Sharing Buttons to this page?'
            help: 'Check if you want sharing buttons to show up on the page.'
            value: 'false'

compress_html:
  ignore:
    envs: [development]
  profile: false
